# Generated by Django 5.0.1 on 2024-01-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApi', '0002_alter_cards_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='posicion',
            field=models.IntegerField(default=1),
        ),
    ]
